repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: make test-unit
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      
      - id: lint
        name: Run linting
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]