steps:
  - id: setup
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-e'
      - '-c'
      # language=bash
      - |
        gcloud secrets versions access latest \
          --secret=cli-test-env-default \
          --project=cloud-builld-webhook \
          --out-file=/root/.env

        # Your current directory is a workspace.
        gcloud auth list
        gsutil cp gs://dnastack-ci-content/bootstrap-workspace.tar.gz /tmp
        cd /tmp
        tar xzf bootstrap-workspace.tar.gz

        gcloud kms decrypt --ciphertext-file=.ssh/github_rsa_key.enc --plaintext-file=.ssh/id_rsa --location=global --keyring=cloud-build-webhook --key=secret_key
        cp -r .ssh /root/
        rm -r .ssh
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/id_rsa

        # Decrypt the pypirc
        gcloud kms decrypt --ciphertext-file=.pypirc.enc --plaintext-file=.pypirc --location=global --keyring=cloud-build-webhook --key=secret_key
        cp .pypirc /root/
        rm .pypirc
        chmod 600 /root/.pypirc

        # Specific setup for the CLI tool
        cd dnastack-client-library

        # Decrypt github (required for deploying to github releases)
        gcloud kms decrypt --ciphertext-file=github.enc --plaintext-file=github --location=global --keyring=cloud-build-webhook --key=secret_key
        cp github /root/
        rm github
        chmod 600 /root/github

        cd ../..
        rm -rf /tmp
    volumes:
      - name: 'homedir'
        path: /root
  # End

  # Build the package
  - id: build-package
    name: python:3.11-slim
    entrypoint: bash
    args:
      - '-ec'
      # language=bash
      - |
        apt update --quiet && apt install -qqy git

        git config --global --add safe.directory /workspace

        # Public release
        #./scripts/build-package.py

        # Pre-release
        ./scripts/build-package.py --pre-release a  # a=alpha, b=beta, rc=release-candidate
    volumes:
      - name: 'homedir'
        path: /root
  # End

  # Perform the sanity check for the CLI
  # NOTE: This is to ensure that the CLI works with the minimum requirements.
  - id: sanity-check
    name: python:3.11-slim
    entrypoint: bash
    args:
      - '-ec'
      # language=bash
      - |
        cp dist/*.whl /tmp
        cd /tmp
        pip install *.whl
        dnastack use --no-auth viral.ai
  # End

  # Test with the oldest stable release of Python.
  - id: python-3.8
    name: python:3.8-slim
    entrypoint: bash
    args:
      - '-ec'
      # language=bash
      - |
        export E2E_ENV_FILE=/root/.env
        ./scripts/run-e2e-tests-in-container.sh
    volumes:
      - name: 'homedir'
        path: /root
  # End

  # Test with the latest stable release of Python.
  # FIXME: At the moment, disable this test to speed up the build process temporarily. Please re-enable when the concurrent tests are possible. (This is PRIORITY ONE.)
#  - id: python-3.11
#    name: python:3.11-slim
#    entrypoint: bash
#    args:
#      - '-ec'
#      # language=bash
#      - |
#        export E2E_ENV_FILE=/root/.env
#        ./scripts/run-e2e-tests-in-container.sh -fv tests/cli/test_*
#    volumes:
#      - name: 'homedir'
#        path: /root
#  # End

  # Test with Anaconda's Python 3
  # FIXME: At the moment, disable this test to speed up the build process temporarily. Please re-enable when the concurrent tests are possible. (This is priority 2.)
#  - id: python-3.x-anaconda
#    name: continuumio/miniconda3
#    entrypoint: bash
#    args:
#      - '-ec'
#      # language=bash
#      - |
#        export E2E_ENV_FILE=/root/.env
#        ./scripts/run-e2e-tests-in-container.sh -fv tests/cli/test_*
#    volumes:
#      - name: 'homedir'
#        path: /root
#  # End

  # Publish the package
  - id: publish-package
    name: python:3.11-slim
    entrypoint: bash
    args:
      - '-ec'
      # language=bash
      - |
        cp /root/.pypirc ~/.pypirc
        pip3 install --quiet twine
        twine upload --verbose --non-interactive --disable-progress-bar dist/*.whl
    volumes:
      - name: 'homedir'
        path: /root
  # End
