name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    
    - name: Run Ruff
      uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3
      with:
        version: "0.12.0"

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    
    - name: Install uv
      uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install package and dependencies
      run: |
        uv sync --group test
    
    - name: Run unit tests with coverage
      run: |
        # Run unit tests using pytest markers
        uv run pytest tests -m unit -v --cov=dnastack --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Python Coverage Comment
      uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac # v3.2
      if: github.event_name == 'pull_request'
      with:
        coverageFile: ./coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.3
        thresholdNew: 0.7
        thresholdModified: 0.0
