name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      with:
        version: "0.12.0"

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install package and dependencies
      run: |
        uv sync --group test
    
    - name: Run unit tests with coverage
      run: |
        # Run unit tests using pytest markers
        uv run pytest tests -m unit -v --cov=dnastack --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Python Coverage Comment
      uses: orgoro/coverage@v3.2
      if: github.event_name == 'pull_request'
      with:
        coverageFile: ./coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.3
        thresholdNew: 0.7
        thresholdModified: 0.0
