name: Build, Test & Analyse

on:
  pull_request:
    branches: [ master, main ]

jobs:
  concourse-build-check:
    name: Concourse Build Check
    uses: DNAstack/dnastack-development-tools/.github/workflows/concourse-build-check.yml@e0cc3b1948f7dfec48fd6ea45f19c96c4046d00e
    with:
      pipeline_name: 'publisher-dev'
      job_name: 'setup-dnastack-client-library-e2e-test-client'
      concourse_username: ${{ vars.CONCOURSE_USERNAME }}
    secrets:
      concourse_password: ${{ secrets.CONCOURSE_PASSWORD }}
