name: Build, Test & Analyse

on:
  pull_request:
    branches: [ master, main ]

jobs:
  concourse-build-check:
    name: Concourse Build Check
    uses: DNAstack/dnastack-development-tools/.github/workflows/concourse-build-check.yml@024fcc6f3e78060821d079f82c139db6dd7a9044
    with:
      pipeline_name: 'publisher-dev'
      job_name: 'setup-dnastack-client-library-e2e-test-client'
      concourse_username: ${{ vars.CONCOURSE_USERNAME }}
    secrets:
      concourse_password: ${{ secrets.CONCOURSE_PASSWORD }}
