name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version-file: .python-version
    
    - name: Install dependencies
      run: |
        uv sync --group dev
    
    - name: Run Ruff
      run: |
        uv run ruff check .
        uv run ruff format --check .